FROM google85/vscode-devcontainer-node:20.11.1

WORKDIR /home/node/app

RUN sudo npm install -g npm@10.5.0

RUN sudo npm install -g @vue/cli-init
RUN sudo npm install -g create-vue@3.9.2

WORKDIR /home/node/app/src
