version: '3'
services:
  node-devcontainer:
    build:
      context: "."
      dockerfile: Dockerfile
    hostname: node-devcontainer
    working_dir: /home/node/app/src
    #env_file:
    #- ../.env
    environment:
        - TZ=Europe/Bucharest
    volumes:
        - ..:/home/node/app
    extra_hosts:
    - "host.docker.internal:host-gateway"
    tty: true # very important
